version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      - run:
          name: Install Python 3.7
          command: apt install python3.7
      - run:
          name: Test role with molecule
          command: |
            python3.7 -m venv venv && \
            . venv/bin/activate && \
            pip install "molecule[lint]" && \
            pip install 'molecule[docker]' && \
            molecule test
workflows:
  version: 2
  all-tests:
    jobs:
      - build