version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      - run:
          name: Test role with molecule
          command: |
            python3 -m venv venv && \
            . venv/bin/activate && \
            pip install --upgrade pip && \
            pip install "molecule[lint]" "molecule[docker]" && \
            cd project && \
            molecule test
workflows:
  version: 2
  all-tests:
    jobs:
      - build